# Generated by Django 3.1 on 2020-08-31 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('sessp', models.CharField(blank=True, max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=255)),
                ('coordenadoria', models.CharField(blank=True, max_length=255)),
                ('setor', models.CharField(blank=True, max_length=255)),
                ('predio', models.CharField(blank=True, max_length=255)),
                ('sala', models.CharField(blank=True, max_length=255)),
                ('ramal', models.CharField(blank=True, max_length=255)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('cpu', models.CharField(blank=True, max_length=255)),
                ('ram', models.CharField(blank=True, max_length=255)),
                ('hd', models.CharField(blank=True, max_length=255)),
                ('tecinic', models.CharField(blank=True, max_length=255)),
                ('tecfim', models.CharField(blank=True, max_length=255)),
                ('patrimonio', models.CharField(blank=True, max_length=255)),
                ('serie', models.CharField(blank=True, max_length=255)),
                ('obs', models.TextField()),
                ('check1', models.BooleanField(default=False)),
                ('check2', models.BooleanField(default=False)),
                ('check3', models.BooleanField(default=False)),
                ('check4', models.BooleanField(default=False)),
                ('check5', models.BooleanField(default=False)),
                ('check6', models.BooleanField(default=False)),
                ('check7', models.BooleanField(default=False)),
                ('check8', models.BooleanField(default=False)),
                ('check9', models.BooleanField(default=False)),
                ('check10', models.BooleanField(default=False)),
                ('check11', models.BooleanField(default=False)),
                ('check12', models.BooleanField(default=False)),
                ('check13', models.BooleanField(default=False)),
                ('check14', models.BooleanField(default=False)),
                ('check15', models.BooleanField(default=False)),
                ('check16', models.BooleanField(default=False)),
            ],
        ),
    ]
