# Generated by Django 3.1 on 2020-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='num_chamado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
